name: Build Signed APK - HTML

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Keystore
        run: |
          cp my-release-key.keystore android/app/my-release-key.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: |
          npx cap sync android
          cd android
          ./gradlew assembleRelease

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: html-app-signed
          path: android/app/build/outputs/apk/**/*.apk
          retention-days: 30
