name: Build Signed APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Setup Keystore
        run: |
          # Copy keystore ke lokasi yang benar
          cp my-release-key.keystore android/app/my-release-key.keystore
          
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        
      - name: Build Release APK
        run: |
          npx cap sync android
          cd android
          ./gradlew assembleRelease
            
      - name: Verify APK signature
        run: |
          cd android/app/build/outputs/apk/release
          jarsigner -verify -verbose -certs app-release.apk
          
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-signed-release
          path: android/app/build/outputs/apk/**/*.apk
          retention-days: 30
